// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages_robocup_ssl_wrapper.proto
// Protobuf Java Version: 4.34.0

package proto.vision;

@com.google.protobuf.Generated
public final class MessagesRobocupSslWrapper extends com.google.protobuf.GeneratedFile {
  private MessagesRobocupSslWrapper() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "MessagesRobocupSslWrapper");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code SSL_Source}
   */
  public enum SSL_Source
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SSL_SOURCE_UNKNOWN = 0;</code>
     */
    SSL_SOURCE_UNKNOWN(0),
    /**
     * <code>SSL_SOURCE_OTHER = 1;</code>
     */
    SSL_SOURCE_OTHER(1),
    /**
     * <code>SSL_SOURCE_SSL_VISION = 2;</code>
     */
    SSL_SOURCE_SSL_VISION(2),
    /**
     * <code>SSL_SOURCE_VISION_PROCESSOR = 3;</code>
     */
    SSL_SOURCE_VISION_PROCESSOR(3),
    /**
     * <code>SSL_SOURCE_GRSIM = 4;</code>
     */
    SSL_SOURCE_GRSIM(4),
    /**
     * <code>SSL_SOURCE_ERFORCE_SIM = 5;</code>
     */
    SSL_SOURCE_ERFORCE_SIM(5),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "SSL_Source");
    }
    /**
     * <code>SSL_SOURCE_UNKNOWN = 0;</code>
     */
    public static final int SSL_SOURCE_UNKNOWN_VALUE = 0;
    /**
     * <code>SSL_SOURCE_OTHER = 1;</code>
     */
    public static final int SSL_SOURCE_OTHER_VALUE = 1;
    /**
     * <code>SSL_SOURCE_SSL_VISION = 2;</code>
     */
    public static final int SSL_SOURCE_SSL_VISION_VALUE = 2;
    /**
     * <code>SSL_SOURCE_VISION_PROCESSOR = 3;</code>
     */
    public static final int SSL_SOURCE_VISION_PROCESSOR_VALUE = 3;
    /**
     * <code>SSL_SOURCE_GRSIM = 4;</code>
     */
    public static final int SSL_SOURCE_GRSIM_VALUE = 4;
    /**
     * <code>SSL_SOURCE_ERFORCE_SIM = 5;</code>
     */
    public static final int SSL_SOURCE_ERFORCE_SIM_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SSL_Source valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SSL_Source forNumber(int value) {
      switch (value) {
        case 0: return SSL_SOURCE_UNKNOWN;
        case 1: return SSL_SOURCE_OTHER;
        case 2: return SSL_SOURCE_SSL_VISION;
        case 3: return SSL_SOURCE_VISION_PROCESSOR;
        case 4: return SSL_SOURCE_GRSIM;
        case 5: return SSL_SOURCE_ERFORCE_SIM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SSL_Source>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SSL_Source> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SSL_Source>() {
            public SSL_Source findValueByNumber(int number) {
              return SSL_Source.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.vision.MessagesRobocupSslWrapper.getDescriptor().getEnumType(0);
    }

    private static final SSL_Source[] VALUES = values();

    public static SSL_Source valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SSL_Source(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SSL_Source)
  }

  public interface SSL_WrapperPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SSL_WrapperPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     * @return Whether the detection field is set.
     */
    boolean hasDetection();
    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     * @return The detection.
     */
    proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame getDetection();
    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     */
    proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder();

    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     * @return Whether the geometry field is set.
     */
    boolean hasGeometry();
    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     * @return The geometry.
     */
    proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData getGeometry();
    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     */
    proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder();

    /**
     * <code>optional .SSL_Source source = 3;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <code>optional .SSL_Source source = 3;</code>
     * @return The source.
     */
    proto.vision.MessagesRobocupSslWrapper.SSL_Source getSource();
  }
  /**
   * Protobuf type {@code SSL_WrapperPacket}
   */
  public static final class SSL_WrapperPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SSL_WrapperPacket)
      SSL_WrapperPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "SSL_WrapperPacket");
    }
    // Use SSL_WrapperPacket.newBuilder() to construct.
    private SSL_WrapperPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SSL_WrapperPacket() {
      source_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.class, proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.class);
    }

    private int bitField0_;
    public static final int DETECTION_FIELD_NUMBER = 1;
    private proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame detection_;
    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     * @return Whether the detection field is set.
     */
    @java.lang.Override
    public boolean hasDetection() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     * @return The detection.
     */
    @java.lang.Override
    public proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame getDetection() {
      return detection_ == null ? proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() : detection_;
    }
    /**
     * <code>optional .SSL_DetectionFrame detection = 1;</code>
     */
    @java.lang.Override
    public proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder() {
      return detection_ == null ? proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() : detection_;
    }

    public static final int GEOMETRY_FIELD_NUMBER = 2;
    private proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData geometry_;
    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     * @return Whether the geometry field is set.
     */
    @java.lang.Override
    public boolean hasGeometry() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     * @return The geometry.
     */
    @java.lang.Override
    public proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData getGeometry() {
      return geometry_ == null ? proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance() : geometry_;
    }
    /**
     * <code>optional .SSL_GeometryData geometry = 2;</code>
     */
    @java.lang.Override
    public proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder() {
      return geometry_ == null ? proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance() : geometry_;
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private int source_ = 0;
    /**
     * <code>optional .SSL_Source source = 3;</code>
     * @return Whether the source field is set.
     */
    @java.lang.Override public boolean hasSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .SSL_Source source = 3;</code>
     * @return The source.
     */
    @java.lang.Override public proto.vision.MessagesRobocupSslWrapper.SSL_Source getSource() {
      proto.vision.MessagesRobocupSslWrapper.SSL_Source result = proto.vision.MessagesRobocupSslWrapper.SSL_Source.forNumber(source_);
      return result == null ? proto.vision.MessagesRobocupSslWrapper.SSL_Source.SSL_SOURCE_UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasDetection()) {
        if (!getDetection().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGeometry()) {
        if (!getGeometry().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getDetection());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getGeometry());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, source_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDetection());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGeometry());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, source_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket)) {
        return super.equals(obj);
      }
      proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket other = (proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket) obj;

      if (hasDetection() != other.hasDetection()) return false;
      if (hasDetection()) {
        if (!getDetection()
            .equals(other.getDetection())) return false;
      }
      if (hasGeometry() != other.hasGeometry()) return false;
      if (hasGeometry()) {
        if (!getGeometry()
            .equals(other.getGeometry())) return false;
      }
      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (source_ != other.source_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDetection()) {
        hash = (37 * hash) + DETECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDetection().hashCode();
      }
      if (hasGeometry()) {
        hash = (37 * hash) + GEOMETRY_FIELD_NUMBER;
        hash = (53 * hash) + getGeometry().hashCode();
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + source_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SSL_WrapperPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SSL_WrapperPacket)
        proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.class, proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.Builder.class);
      }

      // Construct using proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetDetectionFieldBuilder();
          internalGetGeometryFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        detection_ = null;
        if (detectionBuilder_ != null) {
          detectionBuilder_.dispose();
          detectionBuilder_ = null;
        }
        geometry_ = null;
        if (geometryBuilder_ != null) {
          geometryBuilder_.dispose();
          geometryBuilder_ = null;
        }
        source_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.vision.MessagesRobocupSslWrapper.internal_static_SSL_WrapperPacket_descriptor;
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket getDefaultInstanceForType() {
        return proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance();
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket build() {
        proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket buildPartial() {
        proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket result = new proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.detection_ = detectionBuilder_ == null
              ? detection_
              : detectionBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.geometry_ = geometryBuilder_ == null
              ? geometry_
              : geometryBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.source_ = source_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket) {
          return mergeFrom((proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket other) {
        if (other == proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket.getDefaultInstance()) return this;
        if (other.hasDetection()) {
          mergeDetection(other.getDetection());
        }
        if (other.hasGeometry()) {
          mergeGeometry(other.getGeometry());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasDetection()) {
          if (!getDetection().isInitialized()) {
            return false;
          }
        }
        if (hasGeometry()) {
          if (!getGeometry().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetDetectionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetGeometryFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int tmpRaw = input.readEnum();
                proto.vision.MessagesRobocupSslWrapper.SSL_Source tmpValue =
                    proto.vision.MessagesRobocupSslWrapper.SSL_Source.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(3, tmpRaw);
                } else {
                  source_ = tmpRaw;
                  bitField0_ |= 0x00000004;
                }
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame detection_;
      private com.google.protobuf.SingleFieldBuilder<
          proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> detectionBuilder_;
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       * @return Whether the detection field is set.
       */
      public boolean hasDetection() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       * @return The detection.
       */
      public proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame getDetection() {
        if (detectionBuilder_ == null) {
          return detection_ == null ? proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() : detection_;
        } else {
          return detectionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public Builder setDetection(proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (detectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detection_ = value;
        } else {
          detectionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public Builder setDetection(
          proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (detectionBuilder_ == null) {
          detection_ = builderForValue.build();
        } else {
          detectionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public Builder mergeDetection(proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame value) {
        if (detectionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            detection_ != null &&
            detection_ != proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance()) {
            getDetectionBuilder().mergeFrom(value);
          } else {
            detection_ = value;
          }
        } else {
          detectionBuilder_.mergeFrom(value);
        }
        if (detection_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public Builder clearDetection() {
        bitField0_ = (bitField0_ & ~0x00000001);
        detection_ = null;
        if (detectionBuilder_ != null) {
          detectionBuilder_.dispose();
          detectionBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder getDetectionBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetDetectionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      public proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder() {
        if (detectionBuilder_ != null) {
          return detectionBuilder_.getMessageOrBuilder();
        } else {
          return detection_ == null ?
              proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.getDefaultInstance() : detection_;
        }
      }
      /**
       * <code>optional .SSL_DetectionFrame detection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder> 
          internalGetDetectionFieldBuilder() {
        if (detectionBuilder_ == null) {
          detectionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrame.Builder, proto.vision.MessagesRobocupSslDetection.SSL_DetectionFrameOrBuilder>(
                  getDetection(),
                  getParentForChildren(),
                  isClean());
          detection_ = null;
        }
        return detectionBuilder_;
      }

      private proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData geometry_;
      private com.google.protobuf.SingleFieldBuilder<
          proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.Builder, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder> geometryBuilder_;
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       * @return Whether the geometry field is set.
       */
      public boolean hasGeometry() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       * @return The geometry.
       */
      public proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData getGeometry() {
        if (geometryBuilder_ == null) {
          return geometry_ == null ? proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance() : geometry_;
        } else {
          return geometryBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public Builder setGeometry(proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData value) {
        if (geometryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          geometry_ = value;
        } else {
          geometryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public Builder setGeometry(
          proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.Builder builderForValue) {
        if (geometryBuilder_ == null) {
          geometry_ = builderForValue.build();
        } else {
          geometryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public Builder mergeGeometry(proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData value) {
        if (geometryBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            geometry_ != null &&
            geometry_ != proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance()) {
            getGeometryBuilder().mergeFrom(value);
          } else {
            geometry_ = value;
          }
        } else {
          geometryBuilder_.mergeFrom(value);
        }
        if (geometry_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public Builder clearGeometry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        geometry_ = null;
        if (geometryBuilder_ != null) {
          geometryBuilder_.dispose();
          geometryBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.Builder getGeometryBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetGeometryFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      public proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder getGeometryOrBuilder() {
        if (geometryBuilder_ != null) {
          return geometryBuilder_.getMessageOrBuilder();
        } else {
          return geometry_ == null ?
              proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.getDefaultInstance() : geometry_;
        }
      }
      /**
       * <code>optional .SSL_GeometryData geometry = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.Builder, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder> 
          internalGetGeometryFieldBuilder() {
        if (geometryBuilder_ == null) {
          geometryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryData.Builder, proto.vision.MessagesRobocupSslGeometry.SSL_GeometryDataOrBuilder>(
                  getGeometry(),
                  getParentForChildren(),
                  isClean());
          geometry_ = null;
        }
        return geometryBuilder_;
      }

      private int source_ = 0;
      /**
       * <code>optional .SSL_Source source = 3;</code>
       * @return Whether the source field is set.
       */
      @java.lang.Override public boolean hasSource() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .SSL_Source source = 3;</code>
       * @return The source.
       */
      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapper.SSL_Source getSource() {
        proto.vision.MessagesRobocupSslWrapper.SSL_Source result = proto.vision.MessagesRobocupSslWrapper.SSL_Source.forNumber(source_);
        return result == null ? proto.vision.MessagesRobocupSslWrapper.SSL_Source.SSL_SOURCE_UNKNOWN : result;
      }
      /**
       * <code>optional .SSL_Source source = 3;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(proto.vision.MessagesRobocupSslWrapper.SSL_Source value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000004;
        source_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .SSL_Source source = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SSL_WrapperPacket)
    }

    // @@protoc_insertion_point(class_scope:SSL_WrapperPacket)
    private static final proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket();
    }

    public static proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SSL_WrapperPacket>
        PARSER = new com.google.protobuf.AbstractParser<SSL_WrapperPacket>() {
      @java.lang.Override
      public SSL_WrapperPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SSL_WrapperPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SSL_WrapperPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.vision.MessagesRobocupSslWrapper.SSL_WrapperPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SSL_WrapperPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SSL_WrapperPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"messages_robocup_ssl_wrapper.proto\032$me" +
      "ssages_robocup_ssl_detection.proto\032#mess" +
      "ages_robocup_ssl_geometry.proto\"}\n\021SSL_W" +
      "rapperPacket\022&\n\tdetection\030\001 \001(\0132\023.SSL_De" +
      "tectionFrame\022#\n\010geometry\030\002 \001(\0132\021.SSL_Geo" +
      "metryData\022\033\n\006source\030\003 \001(\0162\013.SSL_Source*\250" +
      "\001\n\nSSL_Source\022\026\n\022SSL_SOURCE_UNKNOWN\020\000\022\024\n" +
      "\020SSL_SOURCE_OTHER\020\001\022\031\n\025SSL_SOURCE_SSL_VI" +
      "SION\020\002\022\037\n\033SSL_SOURCE_VISION_PROCESSOR\020\003\022" +
      "\024\n\020SSL_SOURCE_GRSIM\020\004\022\032\n\026SSL_SOURCE_ERFO" +
      "RCE_SIM\020\005B\016\n\014proto.vision"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.vision.MessagesRobocupSslDetection.getDescriptor(),
          proto.vision.MessagesRobocupSslGeometry.getDescriptor(),
        });
    internal_static_SSL_WrapperPacket_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_SSL_WrapperPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SSL_WrapperPacket_descriptor,
        new java.lang.String[] { "Detection", "Geometry", "Source", });
    descriptor.resolveAllFeaturesImmutable();
    proto.vision.MessagesRobocupSslDetection.getDescriptor();
    proto.vision.MessagesRobocupSslGeometry.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
