// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ssl_gc_common.proto
// Protobuf Java Version: 4.34.0

package proto.sim;

@com.google.protobuf.Generated
public final class SslGcCommon extends com.google.protobuf.GeneratedFile {
  private SslGcCommon() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SslGcCommon");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Team is either blue or yellow
   * </pre>
   *
   * Protobuf enum {@code Team}
   */
  public enum Team
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * team not set
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * yellow team
     * </pre>
     *
     * <code>YELLOW = 1;</code>
     */
    YELLOW(1),
    /**
     * <pre>
     * blue team
     * </pre>
     *
     * <code>BLUE = 2;</code>
     */
    BLUE(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "Team");
    }
    /**
     * <pre>
     * team not set
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * yellow team
     * </pre>
     *
     * <code>YELLOW = 1;</code>
     */
    public static final int YELLOW_VALUE = 1;
    /**
     * <pre>
     * blue team
     * </pre>
     *
     * <code>BLUE = 2;</code>
     */
    public static final int BLUE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Team valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Team forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return YELLOW;
        case 2: return BLUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Team>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Team> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Team>() {
            public Team findValueByNumber(int number) {
              return Team.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.sim.SslGcCommon.getDescriptor().getEnumType(0);
    }

    private static final Team[] VALUES = values();

    public static Team valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Team(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Team)
  }

  /**
   * <pre>
   * Division denotes the current division, which influences some rules
   * </pre>
   *
   * Protobuf enum {@code Division}
   */
  public enum Division
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIV_UNKNOWN = 0;</code>
     */
    DIV_UNKNOWN(0),
    /**
     * <code>DIV_A = 1;</code>
     */
    DIV_A(1),
    /**
     * <code>DIV_B = 2;</code>
     */
    DIV_B(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "Division");
    }
    /**
     * <code>DIV_UNKNOWN = 0;</code>
     */
    public static final int DIV_UNKNOWN_VALUE = 0;
    /**
     * <code>DIV_A = 1;</code>
     */
    public static final int DIV_A_VALUE = 1;
    /**
     * <code>DIV_B = 2;</code>
     */
    public static final int DIV_B_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Division valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Division forNumber(int value) {
      switch (value) {
        case 0: return DIV_UNKNOWN;
        case 1: return DIV_A;
        case 2: return DIV_B;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Division>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Division> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Division>() {
            public Division findValueByNumber(int number) {
              return Division.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.sim.SslGcCommon.getDescriptor().getEnumType(1);
    }

    private static final Division[] VALUES = values();

    public static Division valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Division(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Division)
  }

  public interface RobotIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RobotId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .Team team = 2;</code>
     * @return Whether the team field is set.
     */
    boolean hasTeam();
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .Team team = 2;</code>
     * @return The team.
     */
    proto.sim.SslGcCommon.Team getTeam();
  }
  /**
   * <pre>
   * RobotId is the combination of a team and a robot id
   * </pre>
   *
   * Protobuf type {@code RobotId}
   */
  public static final class RobotId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RobotId)
      RobotIdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "RobotId");
    }
    // Use RobotId.newBuilder() to construct.
    private RobotId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RobotId() {
      team_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.sim.SslGcCommon.internal_static_RobotId_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return proto.sim.SslGcCommon.internal_static_RobotId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.sim.SslGcCommon.internal_static_RobotId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.sim.SslGcCommon.RobotId.class, proto.sim.SslGcCommon.RobotId.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TEAM_FIELD_NUMBER = 2;
    private int team_ = 0;
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .Team team = 2;</code>
     * @return Whether the team field is set.
     */
    @java.lang.Override public boolean hasTeam() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .Team team = 2;</code>
     * @return The team.
     */
    @java.lang.Override public proto.sim.SslGcCommon.Team getTeam() {
      proto.sim.SslGcCommon.Team result = proto.sim.SslGcCommon.Team.forNumber(team_);
      return result == null ? proto.sim.SslGcCommon.Team.UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, team_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, team_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.sim.SslGcCommon.RobotId)) {
        return super.equals(obj);
      }
      proto.sim.SslGcCommon.RobotId other = (proto.sim.SslGcCommon.RobotId) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasTeam() != other.hasTeam()) return false;
      if (hasTeam()) {
        if (team_ != other.team_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasTeam()) {
        hash = (37 * hash) + TEAM_FIELD_NUMBER;
        hash = (53 * hash) + team_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.sim.SslGcCommon.RobotId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.sim.SslGcCommon.RobotId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.sim.SslGcCommon.RobotId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.sim.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.sim.SslGcCommon.RobotId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * RobotId is the combination of a team and a robot id
     * </pre>
     *
     * Protobuf type {@code RobotId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RobotId)
        proto.sim.SslGcCommon.RobotIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.sim.SslGcCommon.internal_static_RobotId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.sim.SslGcCommon.internal_static_RobotId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.sim.SslGcCommon.RobotId.class, proto.sim.SslGcCommon.RobotId.Builder.class);
      }

      // Construct using proto.sim.SslGcCommon.RobotId.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        team_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.sim.SslGcCommon.internal_static_RobotId_descriptor;
      }

      @java.lang.Override
      public proto.sim.SslGcCommon.RobotId getDefaultInstanceForType() {
        return proto.sim.SslGcCommon.RobotId.getDefaultInstance();
      }

      @java.lang.Override
      public proto.sim.SslGcCommon.RobotId build() {
        proto.sim.SslGcCommon.RobotId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.sim.SslGcCommon.RobotId buildPartial() {
        proto.sim.SslGcCommon.RobotId result = new proto.sim.SslGcCommon.RobotId(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.sim.SslGcCommon.RobotId result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.team_ = team_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.sim.SslGcCommon.RobotId) {
          return mergeFrom((proto.sim.SslGcCommon.RobotId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.sim.SslGcCommon.RobotId other) {
        if (other == proto.sim.SslGcCommon.RobotId.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTeam()) {
          setTeam(other.getTeam());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int tmpRaw = input.readEnum();
                proto.sim.SslGcCommon.Team tmpValue =
                    proto.sim.SslGcCommon.Team.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  team_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int team_ = 0;
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .Team team = 2;</code>
       * @return Whether the team field is set.
       */
      @java.lang.Override public boolean hasTeam() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .Team team = 2;</code>
       * @return The team.
       */
      @java.lang.Override
      public proto.sim.SslGcCommon.Team getTeam() {
        proto.sim.SslGcCommon.Team result = proto.sim.SslGcCommon.Team.forNumber(team_);
        return result == null ? proto.sim.SslGcCommon.Team.UNKNOWN : result;
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .Team team = 2;</code>
       * @param value The team to set.
       * @return This builder for chaining.
       */
      public Builder setTeam(proto.sim.SslGcCommon.Team value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        team_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .Team team = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        team_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RobotId)
    }

    // @@protoc_insertion_point(class_scope:RobotId)
    private static final proto.sim.SslGcCommon.RobotId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.sim.SslGcCommon.RobotId();
    }

    public static proto.sim.SslGcCommon.RobotId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RobotId>
        PARSER = new com.google.protobuf.AbstractParser<RobotId>() {
      @java.lang.Override
      public RobotId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RobotId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RobotId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.sim.SslGcCommon.RobotId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RobotId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RobotId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ssl_gc_common.proto\"*\n\007RobotId\022\n\n\002id\030\001" +
      " \001(\r\022\023\n\004team\030\002 \001(\0162\005.Team*)\n\004Team\022\013\n\007UNK" +
      "NOWN\020\000\022\n\n\006YELLOW\020\001\022\010\n\004BLUE\020\002*1\n\010Division" +
      "\022\017\n\013DIV_UNKNOWN\020\000\022\t\n\005DIV_A\020\001\022\t\n\005DIV_B\020\002B" +
      "C\n\tproto.simZ6github.com/RoboCup-SSL/ssl" +
      "-simulation-protocol/pkg/sim"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RobotId_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_RobotId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RobotId_descriptor,
        new java.lang.String[] { "Id", "Team", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
